### ISSUE TITLE
easy_logger_wrapper in easy_localization?

### ISSUE THREAD

**Issue by sinxwal** [atidev/ATI.SU-Flutter-Template-Project#8]
Можете объяснить на пальцах как это устроено?

**Comment by levitckii-daniil** [comment]
EasyLoggerWrapper позволяет связать внутренний Logger в EasyLocalization с Logger, который мы используем в проекте (тот, который находится singleton-ом в DI дереве). То есть этот класс необходим, чтобы логи от EasyLocalization были в том же формате, что и остальные логи в проекте. Функция stubLog нужна для того, чтобы было возможно отключить логи 
```dart
enableEasyLocalizationLogs ? easyLoggerWrapper.log : easyLoggerWrapper.stubLog
```

Приносим извинения за длительный ответ, потерялись уведомления на issue.
